### ISSUE TITLE
Eliminate need of PVC for mattermost-push-proxy

### ISSUE THREAD

**Issue by aditya-konarde** [rhdt/chat-push-proxy#7]
MM-push-proxy uses the persistent volume claim named mattermost-push-proxy-config to load the mattermost-push-proxy.json. We need to eliminate the need for a persistent volume claim here and have the config into the image itself. Image is built from [here](https://github.com/syamgk/mm-push-proxy/tree/master/3.10.0)

Once upstream image is modified and built, we can remove the PVC reference from the template.

**Comment by syamgk** [comment]
https://github.com/rhdt/chat-push-proxy/pull/8

the Docker image is also updated so as to work without PVC

**Comment by aditya-konarde** [comment]
#8 Merged. Closing this issue.
